WIP - use mamba env vars, update docker-stacks scripts, add healthcheck, activate birdy environment
Signed-off-by: Trevor James Smith <10819524+Zeitsperre@users.noreply.github.com>

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -33,31 +33,20 @@ RUN if grep -q '^ID=alpine$' /etc/os-release; then \
     :
 ENV MAMBA_USER=$NEW_MAMBA_USER
 
+# Alias UID and GID for use with docker-stacks
+ENV NB_USER=${MAMBA_USER}
+ARG NB_GID="${NEW_MAMBA_USER_GID}"
+
 # Copy environment file
 COPY --chown=$MAMBA_USER:$MAMBA_USER environment.yml /tmp/environment.yml
 
-# Add additional fonts for matplotlib and widgets
+# Add additional fonts and x11-utils for matplotlib and firefox support
 RUN apt-get update && \
-    apt-get install --yes fonts-humor-sans && \
+    apt-get install --yes fonts-humor-sans x11-utils && \
     apt-get clean
 
-# create env "birdy"
+# Create "birdy" environment
 # use umask 0000 so that the files for the new environment are usable by user 'jenkins' for the jupyter-conda-extension
-#
-# Perform two-stage install because one single 'conda env create -f /environment.yml'
-# was taking forever to complete, same with mamba.
-# Previously, one single 'conda env create -f /environment.yml' took forever because we
-# removed all direct dependencies of xclim and ravenpy in /environment.yml for
-# dependencies pinning by xclim and ravenpy to take effect.
-# This resulted in conda having a lot more packages to "solve" and it seems the solver
-# performance dropped exponentially with the number of packages to solve.
-#
-# Conda was stuck at this step:
-# DEBUG conda.common._logic:_run_sat(607): Invoking SAT with clause count: 2500273
-#
-# As of March 2026, the new image uses mambaorg/micromamba and the libmamba solver by default. 
-
-# Create birdy environment
 RUN umask 0000 && \
     micromamba create --name birdy --file /tmp/environment.yml "python>=3.12,<3.13" --yes && \
     micromamba clean --all --yes
@@ -66,12 +55,10 @@ RUN umask 0000 && \
 RUN umask 0000 && \
     micromamba run --name birdy python -m ipykernel install --name birdy && \
     micromamba env export --name birdy | tee /conda-env-export-final.yml && \
-    du -sh /opt/conda | tee /conda-envs-size-final.txt
+    du -sh "${MAMBA_ROOT_PREFIX}" | tee /conda-envs-size-final.txt
 
-# This should be "master" but commit
-# https://github.com/jupyter/docker-stacks/commit/c772e98ac794173d6ed83a08ec249038b27ca3be
-# is breaking with us since we do not have user jovyan.
-ENV DOCKER_STACKS_COMMIT=709206ac8788475728cc9c992c25fb5f1501bc29
+# Docker-stacks commit from last time base-notebook was modified (2025/05/24)
+ENV DOCKER_STACKS_COMMIT=e73d308ba06fd5bcc75a4ee8417711743860c964
 
 # Activate base environment
 ARG MAMBA_DOCKERFILE_ACTIVATE=1
@@ -83,45 +70,47 @@ ARG MAMBA_DOCKERFILE_ACTIVATE=1
 # hardcoded so users can copy the nb to writable-workspace/ dir and still be able
 # to run them seemlessly from the Jupyter env (without having to also copy
 # those *.geojson files with the notebooks).
-RUN wget https://raw.githubusercontent.com/jupyter/docker-stacks/$DOCKER_STACKS_COMMIT/base-notebook/start.sh --output-document /usr/local/bin/start.sh && \
-    wget https://raw.githubusercontent.com/jupyter/docker-stacks/$DOCKER_STACKS_COMMIT/base-notebook/start-singleuser.sh --output-document /usr/local/bin/start-singleuser.sh && \
-    wget https://raw.githubusercontent.com/jupyter/docker-stacks/$DOCKER_STACKS_COMMIT/base-notebook/start-notebook.sh --output-document /usr/local/bin/start-notebook.sh && \
-    wget https://raw.githubusercontent.com/jupyter/docker-stacks/$DOCKER_STACKS_COMMIT/base-notebook/fix-permissions --output-document /usr/local/bin/fix-permissions && \
+RUN wget https://raw.githubusercontent.com/jupyter/docker-stacks/$DOCKER_STACKS_COMMIT/images/base-notebook/start-singleuser.py --output-document /usr/local/bin/start-singleuser.py && \
+    wget https://raw.githubusercontent.com/jupyter/docker-stacks/$DOCKER_STACKS_COMMIT/images/base-notebook/start-notebook.py --output-document /usr/local/bin/start-notebook.py && \
     mkdir /etc/jupyter && \
-    wget https://raw.githubusercontent.com/jupyter/docker-stacks/$DOCKER_STACKS_COMMIT/base-notebook/jupyter_notebook_config.py --output-document /etc/jupyter/jupyter_notebook_config.py && \
-    chmod a+rx /usr/local/bin/start.sh /usr/local/bin/start-singleuser.sh /usr/local/bin/start-notebook.sh /usr/local/bin/fix-permissions && \
-    chmod a+r /etc/jupyter/jupyter_notebook_config.py && \
+    wget https://raw.githubusercontent.com/jupyter/docker-stacks/$DOCKER_STACKS_COMMIT/images/base-notebook/jupyter_server_config.py --output-document /etc/jupyter/jupyter_server_config.py && \
+    wget https://raw.githubusercontent.com/jupyter/docker-stacks/$DOCKER_STACKS_COMMIT/images/base-notebook/docker_healthcheck.py --output-document /etc/jupyter/docker_healthcheck.py && \
+    chmod a+rx /usr/local/bin/start-singleuser.py /usr/local/bin/start-notebook.py /etc/jupyter/docker_healthcheck.py && \
+    chmod a+r /etc/jupyter/jupyter_server_config.py && \
     mkdir -p /notebook_dir/writable-workspace && \
     chown "${MAMBA_USER}" /notebook_dir/writable-workspace && \
     mkdir -p /notebook_dir/pavics-homepage && \
     chown "${MAMBA_USER}" /notebook_dir/pavics-homepage && \
     chown root:root /notebook_dir && \
     chmod a-w /notebook_dir && \
-    mkdir -p /opt/conda/envs/birdy/fonts && \
-    chmod a+rwX -R /opt/conda/envs/birdy/fonts && \
-    mkdir -p /opt/conda/pkgs/cache && \
-    chown "${MAMBA_USER}":"${MAMBA_USER}" -R /opt/conda/pkgs/cache && \
-    touch /opt/conda/pkgs/pkgs.lock && \
-    chown "${MAMBA_USER}":"${MAMBA_USER}" /opt/conda/pkgs/pkgs.lock && \
+    mkdir -p "${MAMBA_ROOT_PREFIX}/envs/birdy/fonts" && \
+    chmod a+rwX -R "${MAMBA_ROOT_PREFIX}/envs/birdy/fonts" && \
+    mkdir -p "${MAMBA_ROOT_PREFIX}/pkgs/cache" && \
+    chown "${MAMBA_USER}":"${MAMBA_USER}" -R "${MAMBA_ROOT_PREFIX}/pkgs/cache" && \
+    touch "${MAMBA_ROOT_PREFIX}/pkgs/pkgs.lock" && \
+    chown "${MAMBA_USER}":"${MAMBA_USER}" "${MAMBA_ROOT_PREFIX}/pkgs/pkgs.lock" && \
     mkdir -p /usr/local/bin && \
     wget https://downloads.globus.org/globus-connect-personal/linux/stable/globusconnectpersonal-latest.tgz -O /usr/local/bin/globusconnectpersonal-latest.tgz && \
     tar xzf /usr/local/bin/globusconnectpersonal-latest.tgz -C /usr/local/bin/ && \
     ln -vs /usr/local/bin/globusconnectpersonal*/globusconnectpersonal /usr/local/bin/globusconnectpersonal && \
     rm -v /usr/local/bin/globusconnectpersonal-latest.tgz
 
+# Set birdy as the default kernel
+RUN echo "c.MultiKernelManager.default_kernel_name = 'birdy'" >> /etc/jupyter/jupyter_server_config.py
+
 # For jupyter-panel-proxy launcher.
 ENV BOKEH_ALLOW_WS_ORIGIN="*"
 
 # To supply the location of the RavenHydroFramework binary
 # FIXME: This location should be provided via the raven-hydro package which would help with the discovery logic in RavenPy
-ENV RAVENPY_RAVEN_BINARY_PATH="/opt/conda/envs/birdy/bin/raven"
+ENV RAVENPY_RAVEN_BINARY_PATH="${MAMBA_ROOT_PREFIX}/envs/birdy/bin/raven"
 
 # For import xesmf since esmf-8.4.0, see: https://github.com/conda-forge/esmf-feedstock/issues/91
-ENV ESMFMKFILE="/opt/conda/envs/birdy/lib/esmf.mk"
+ENV ESMFMKFILE="${MAMBA_ROOT_PREFIX}/envs/birdy/lib/esmf.mk"
 
-# To avoid error "PROJ: proj_create_from_database: Open of /opt/conda/envs/birdy/share/proj failed"
+# To avoid error "PROJ: proj_create_from_database: Open of ${MAMBA_ROOT_PREFIX}/envs/birdy/share/proj failed"
 # This simulates a real `conda activate birdy`.
-ENV PROJ_DATA="/opt/conda/envs/birdy/share/proj"
+ENV PROJ_DATA="${MAMBA_ROOT_PREFIX}/envs/birdy/share/proj"
 
 # To expose conda-installed compilers so that users can make use of them
 ENV gcc=x86_64-conda-linux-gnu-gcc
@@ -131,12 +120,17 @@ ENV gfortran=x86_64-conda-linux-gnu-gfortran
 # JupyterLab cannot write to hidden folders by design
 ENV XDG_CACHE_HOME="/home/${MAMBA_USER}/cache"
 
-# problem running start-notebook.sh when being root
+# Healthcheck - Requires NB_USER variable (copied from Docker-stacks)
+HEALTHCHECK --interval=3s --timeout=1s --start-period=3s --retries=3 CMD /etc/jupyter/docker_healthcheck.py || exit 1
+
+# Problem running start-notebook.sh when being root
 # the jupyter/base-notebook image also do not default to root user so we do the same here
 USER $MAMBA_USER
-# set entrypoint for jenkins to root
+# Activate birdy environment
+ENV ENV_NAME=birdy
+# Set entrypoint for jenkins to root directory
 WORKDIR /
 
 # follow jupyter/base-notebook image so config in jupyterhub is simpler
 # start notebook in conda environment to have working jupyter extensions
-CMD ["/usr/local/bin/_entrypoint.sh", "run", "/usr/local/bin/start-notebook.sh"]
+CMD ["/usr/local/bin/_entrypoint.sh", "run", "-n", "base", "/usr/local/bin/start-notebook.py"]
